### ISSUE TITLE
Woorkbook Subject/Title

### ISSUE THREAD

**Issue by TBehrmann** [dhatim/fastexcel#164]
Is it possible to set the title of an Excel file? That is, the title that can then be queried in the programme under Information.

**Comment by ochedru** [comment]
Do you mean the "title" attribute that appear in the "summary" tab of the "properties" dialog box in Excel?

**Comment by meiMingle** [comment]
@ochedru Hello, I am working on this issue, but I have encountered some problems, and I would like to ask you for advice. When setting custom attributes, the fmtid and pid attributes in the custom.xml file are both necessary. Among them, pid I guess is an index value that increases with the number of attributes. The value of fmtid looks more like it is created by some method. Calculated, because modifying any of the character files will report an error, this fixed value is copied from a file created by MicrosoftExcel. Do you have any suggestions for this? The relevant code is in line 183~214 of the WorkBook.java file branched below
https://github.com/meiMingle/fastexcel/tree/feature-support_setting_properties
