### ISSUE TITLE
Date CellType reader not supported by fasterexcel reader libarary

### ISSUE THREAD

**Issue by naveensingh10** [dhatim/fastexcel#91]

**Comment by ochedru** [comment]
Fastexcel does provide method `Cell.asDate()`. Can you post a code snippet regarding your problem?

**Comment by 2knu** [comment]
I think I have the same Problem. How can I decide if its a Date cell or just a number cell?
I want to read different excel sheets, where I don't know which one is a date cell. 

There is only a CellType Number and not a Date type. So I could try to read every number as Date, but than numbers will be read wrong for me, because they arent dates.

So what I would expect is:

```
if (cell.getType() == CellType.Date)
{ cell.asDate(); }
else if(cell.getType() == CellType.Number)
{ cell.asNumber(); }
else 
{ cell.getText(); }
```

Would be nice when smt. like this will work :)

**Comment by ochedru** [comment]
Dates are actually stored as numbers in Excel worksheets. Check out e.g. [`DateUtil.isCellDateFormatted()`](https://poi.apache.org/apidocs/4.1/org/apache/poi/ss/usermodel/DateUtil.html#isCellDateFormatted-org.apache.poi.ss.usermodel.Cell-) in Apache POI.
They are displayed as dates using cell formatting. There is no such thing as a date cell type.
